import { createContext } from "react";

const defaultContext = {
  transaction: [],
  filteredTransactions: [],
  mode: false,
  expenseDate: "",
  desc: "",
  category: "All",
  incomeType: "All",
  amount: "",
  userType: "Viewer",
  totalIncome: 0,
  totalExpense: 0,
  totalBalance: 0,
  totalExpenseTransaction: 0,
  firstFiveTransac: [],
  houseExpense: 0,
  foodExpense: 0,
  entertainmentExpense: 0,
  transportExpense: 0,
  healthExpense: 0,
  shoppingExpense: 0,
  highestExpenseTransaction: 0,
  highestPercentExpense: 0,
  monthlyComparison: [],
  editTransaction: null,

  toggleMode: () => {},
  newExpense: () => {},
  setExpenseDate: () => {},
  setDesc: () => {},
  setCategory: () => {},
  setIncomeType: () => {},
  setAmount: () => {},
  filterByIncome: () => {},
  setSearchTransac: () => {},
  setUserType: () => {},
  deleteExpense: () => {},
  editExp: () => {},
  updateExpense: () => {},
  setEditTransaction: () => {},
};

export const FintrackContext = createContext(defaultContext);
